.PHONY: clean All

All:
	@echo "----------Building project:[ Proj1_FirstCPP - Debug ]----------"
	@cd "Proj1_FirstCPP" && "$(MAKE)" -f  "Proj1_FirstCPP.mk"
clean:
	@echo "----------Cleaning project:[ Proj1_FirstCPP - Debug ]----------"
	@cd "Proj1_FirstCPP" && "$(MAKE)" -f  "Proj1_FirstCPP.mk" clean
