.PHONY: clean All

All:
	@echo "----------Building project:[ FirstCPP_Program - Debug ]----------"
	@cd "FirstCPP_Program" && "$(MAKE)" -f  "FirstCPP_Program.mk"
clean:
	@echo "----------Cleaning project:[ FirstCPP_Program - Debug ]----------"
	@cd "FirstCPP_Program" && "$(MAKE)" -f  "FirstCPP_Program.mk" clean
